import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface Recipe {
    recipe_name: string;
    summary: string;
    prep_time: string;
    servings: string;
    nutritional_info?: {
        calories: string;
    };
    ingredients: string[];
    instructions: any[]; // Can be string[] or object[] depending on parsing
}

export const generateRecipePDF = (recipe: Recipe) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const margin = 20;
    let yPos = 20;

    // Title
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text(recipe.recipe_name, margin, yPos);
    yPos += 15;

    // Summary
    if (recipe.summary) {
        doc.setFontSize(11);
        doc.setFont("helvetica", "normal");
        const summaryLines = doc.splitTextToSize(recipe.summary, pageWidth - 2 * margin);
        doc.text(summaryLines, margin, yPos);
        yPos += (summaryLines.length * 5) + 10;
    }

    // Metadata Grid
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    const metaLabels = ["Prep Time", "Servings", "Calories"];
    const metaValues = [
        recipe.prep_time || "N/A",
        recipe.servings || "N/A",
        recipe.nutritional_info?.calories ? `${recipe.nutritional_info.calories} kcal` : "N/A"
    ];

    let xPos = margin;
    metaLabels.forEach((label, i) => {
        doc.text(label, xPos, yPos);
        doc.setFont("helvetica", "normal");
        doc.text(metaValues[i], xPos, yPos + 6);
        doc.setFont("helvetica", "bold");
        xPos += 50;
    });
    yPos += 20;

    // Ingredients Section
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Ingredients", margin, yPos);
    yPos += 10;

    // Process ingredients for table
    const ingredientRows = recipe.ingredients.map(ing => [ing]);

    autoTable(doc, {
        startY: yPos,
        head: [],
        body: ingredientRows,
        theme: 'plain',
        styles: { fontSize: 11, cellPadding: 3 },
        margin: { left: margin },
    });

    // @ts-ignore
    yPos = doc.lastAutoTable.finalY + 15;

    // Instructions Section
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Instructions", margin, yPos);
    yPos += 10;

    // Process instructions
    // Handle both string[] and object[] format
    const instructionRows = recipe.instructions.map((inst, index) => {
        let text = "";
        if (typeof inst === "string") {
            text = inst;
        } else if (typeof inst === "object" && inst.instruction) {
            text = inst.instruction;
        } else {
            text = JSON.stringify(inst);
        }
        return [index + 1, text];
    });

    autoTable(doc, {
        startY: yPos,
        head: [],
        body: instructionRows,
        theme: 'plain',
        styles: { fontSize: 11, cellPadding: 4 },
        columnStyles: {
            0: { cellWidth: 10, fontStyle: 'bold' },
            1: { cellWidth: 'auto' }
        },
        margin: { left: margin },
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(9);
        doc.setFont("helvetica", "italic");
        doc.text(
            "Generated by OChef - Your Smart Kitchen Companion",
            pageWidth / 2,
            doc.internal.pageSize.height - 10,
            { align: "center" }
        );
    }

    // Download
    doc.save(`${recipe.recipe_name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`);
};
